config/routes.rb
Rails.application.routes.draw do
  
  devise_for :customers, controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}


 devise_for :admin, controllers: {
  sessions: "admin/sessions"
}


  scope module: :public do
    root :to => "homes#top"
    get "about" => "homes#about"
    get 'customers/my_page' => 'customers#show'
    get 'customers/information/edit' => 'customers#edit'
    patch 'customers/information/edit' => 'customers#update'
    get 'customers/confirm' => 'customers#confirm'
    patch 'customers/leave' => 'customers#leave'
    resources :items, only: [:index, :show]
    delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
    resources :cart_items, only: [:index, :update, :destroy, :create]
    get 'orders/complete' => 'orders#complete'
    resources :orders, only: [:new, :create, :index, :show]
    post 'orders/confirm' => 'orders#confirm'
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
    get "items/:id/genre_search" => "items#search", as: "genre_search"
  end
  namespace :admin do
    root :to =>  'homes#top'
    resources :customers, only: [:index, :show, :edit, :update]
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :orders, only: [:show, :update] do
      resources :order_items, only: [:update]
    end
  end
 

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
  validates :name, presence:true
  validates :address, presence:true
  validates :post_code, presence:true, length: { is: 7 }, numericality: true
  
  def address_display
    '〒' + post_code + '　宛先' + address + '　宛名' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item
  
  def with_tax_price
    (item.price * 1.1).floor
  end
  
  def subtotal_price
    item.with_tax_price * quantity
  end
  
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  validates :email, presence: true
  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_reading, presence: true, format: { with: /\A[\p{katakana}\p{blank}ー－]+\z/}
  validates :first_name_reading, presence: true, format: { with: /\A[\p{katakana}\p{blank}ー－]+\z/}
  validates :post_code, presence: true
  validates :address, presence: true
  validates :phone_number, presence: true

  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  
  
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :cart_items, dependent: :destroy
  has_many :order_items, dependent: :destroy
  has_many :tags

  validates :name, presence:true
  validates :explanation, presence:true
  validates :price, presence:true, numericality: {greater_than_or_equal_to: 1}

  has_one_attached :item_image
  
  def with_tax_price
    (price * 1.1).floor
  end

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_items, dependent: :destroy
 
 enum payment_option: { credit_card: 0, transfer: 1 }
 
 def address_display
    '〒' + post_code + '　宛先' + address + '　宛名' + name
 end
 
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :item
  belongs_to :order

end

app/models/tag.rb
class Tag < ApplicationRecord
  belongs_to :item
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  
  def index
    @customers = Customer.all
  end
  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      flash[:customer_information_update] = "変更内容を保存しました"
      redirect_to admin_customer_path
    else
      render :edit
    end
  end

  private
  def customer_params
    params.require(:customer).permit(:email, :last_name, :first_name, :last_name_reading, :first_name_reading, :post_code, :address, :phone_number, :is_deleted)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
   def top
    @params = params[:id]
    @order = Order.where(customer_id: @params).order(created_at: :desc)
    @orders = Order.all
   end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

  def index
    @items = Item.all
  end
  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    tags = Vision.get_image_data(item_params[:item_image])
    if @item.save
      tags.each do |tag|
        @item.tags.create(name: tag)
      end
      redirect_to admin_item_path(@item)
    else
      render "new"
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path(@item)
    else
      render "edit"
    end
  end
   private

  def item_params
    params.require(:item).permit(:name, :explanation, :price, :is_active, :item_image)
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
   def show
    @order = Order.find(params[:id])
    @orders = Order.all
    
  
   end

  def update
    @order = Order.find(params[:id])
    @order_details = OrderItem.where(order_id: @order)

    
  end

  private

  
end

app/controllers/admin/passwords_controller.rb
# frozen_string_literal: true

class Admin::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_admin!, if: :admin_url 

  def admin_url
    request.fullpath.include?("/admin")
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_items_helper.rb
module Admin::OrderItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/customers/edit.html.erb
<h1>会員情報編集アド</h1>

app/views/admin/customers/index.html.erb
<h1>会員情報一覧アド</h1>
<div class="container">
  <div class="row">
    <div class="col-1"></div>
    <div class="col-10 col-offset-1">
      <h4 class="my-3 px-4 bg-light font-weight-bold">会員一覧</h4>
      <table class="table">
        <thead>
          <tr>
            <th>会員ID</th>
            <th>氏名</th>
            <th>メールアドレス</th>
            <th>ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @customers.each do |customer| %>
          <tr>
            <td><%= customer.id %></td>
            <td><%= link_to customer.last_name + customer.first_name, admin_customer_path(customer.id) %></td>
            <td><%= customer.email %></td>
            <td><% if customer.is_deleted == true %>
                  退会
                <% else %>
                  有効
                <% end %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/customers/show.html.erb
<h1>会員情報詳細アド</h1>
<div class="container">
  <div class="row">
    <div class="col-1"></div>
    <div class="col-10 col-offset-1">
      <h4 class="my-3 px-4 bg-light font-weight-bold"><%= @customer.last_name %><%= @customer.first_name %>さんの会員詳細</h4>
      <table class="table">
        <tbody>
          <tr>
            <td>会員ID</td>
            <td><%= @customer.id %></td>
          </tr>
          <tr>
            <td>氏名</td>
            <td><%= @customer.last_name %>　<%= @customer.first_name %></td>
          </tr>
          <tr>
            <td>フリガナ</td>
            <td><%= @customer.last_name_reading %>　<%= @customer.first_name_reading%></td>
          </tr>
          <tr>
            <td>郵便番号</td>
            <td><%= @customer.post_code %></td>
          </tr>
          <tr>
            <td>住所</td>
            <td><%= @customer.address %></td>
          </tr>
          <tr>
            <td>電話番号</td>
            <td><%= @customer.phone_number %></td>
          </tr>
          <tr>
            <td>メールアドレス</td>
            <td><%= @customer.email %></td>
          </tr>
          <tr>
            <td>会員ステータス</td>
            <td><% if @customer.is_deleted == true %>
                  退会
                <% else %>
                  有効
                <% end %></td>
          </tr>
          <tr>
            <td></td>
            <% if Order.find_by(customer_id: @customer.id) %>
              <td><%= link_to "編集する", edit_admin_customer_path, class:"btn btn-success" %>　　<%= link_to "注文履歴一覧を見る", admin_root_path, class:"btn btn-info" %></td>
            <% else %>
              <td><%= link_to "編集する", edit_admin_customer_path, class:"btn btn-success" %></td>
            <% end %>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/items/_from.html.erb
<%= form_with model: [:admin, @item], local: true do |f| %>
    <div class="row form-group">
      <label class="col-md-2 offset-md-2">商品画像</label>
      <div class="col-md-6"><%= f.file_field :item_image, accept: 'image/*' %></div>
    </div>
    <div class="row form-group">
      <label class="col-md-2 offset-md-2">商品名</label>
      <div class="col-md-6"><%= f.text_field :name, placeholder: "商品名", class: "form-control" %></div>
    </div>
    <div class="row form-group">
      <label class="col-md-2 offset-md-2">商品説明</label>
      <div class="col-md-6">
        <%= f.text_area :explanation, placeholder: "ここに説明文を記述します", class: "form-control", size: "100x10" %>
      </div>
    </div>
   
    <div class="row form-group">
      <label class="col-md-2 offset-md-2">税抜き価格</label>
      <div class="col-md-6"><%= f.text_field :price, placeholder: "000", class: "form-control" %></div>円
    </div>
    <div class="row">
      <div class="col-md-2 offset-md-5">
        <% if f.object.new_record? %>
          <%= f.submit "新規登録", class: "btn-lg btn-success" %>
        <% else %>
          <%= f.submit "変更を保存", class: "btn-lg btn-success" %>
        <% end %>
      </div>
    </div>
  <% end %>

app/views/admin/items/edit.html.erb
<h3>商品編集</h3>
  <%= form_with model: [:admin, @item], local: true do |f| %>
    <div class="row form-group">
      <label class="col-md-2 offset-md-2">商品画像</label>
      <div class="col-md-6"><%= f.file_field :item_image, accept: 'image/*' %></div>
    </div>
    <div class="row form-group">
      <label class="col-md-2 offset-md-2">商品名</label>
      <div class="col-md-6"><%= f.text_field :name, placeholder: "商品名", class: "form-control" %></div>
    </div>
    <div class="row form-group">
      <label class="col-md-2 offset-md-2">商品説明</label>
      <div class="col-md-6">
        <%= f.text_area :explanation, placeholder: "ここに説明文を記述します", class: "form-control", size: "100x10" %>
      </div>
    </div>
   
    <div class="row form-group">
      <label class="col-md-2 offset-md-2">税抜き価格</label>
      <div class="col-md-6"><%= f.text_field :price, placeholder: "000", class: "form-control" %></div>円
    </div>
    <div class="row">
      <div class="col-md-2 offset-md-5">
        <% if f.object.new_record? %>
          <%= f.submit "新規登録", class: "btn-lg btn-success" %>
        <% else %>
          <%= f.submit "変更を保存", class: "btn-lg btn-success" %>
        <% end %>
      </div>
    </div>
  <% end %>

app/views/admin/items/index.html.erb
<div class= "container">
  <div class="row mt-5">
    <h4 class="col-4 text-center bg-light">商品一覧</h4>
    <div class="col-1 offset-7">
    <%= link_to new_admin_item_path do %>
      <i class="fa-regular fa-square-plus fa-2xl" style="color: #000000;"></i>
    <% end %>
    </div>
  </div>

  <br>
  <table class="table">
    <thead>
      <tr class="bg-light">
        <th>商品ID</th>
        <th>商品名</th>
        <th>税抜価格</th>
      </tr>
    </thead>
    <tbody>
      <% @items.each do |item| %>
        <tr>
          <td><%=image_tag item.item_image, size:'50x50' %>   <%= item.id %></td>
          <td><u><%=link_to item.name, admin_item_path(item), class: "text-dark" %></u></td>
          <td><%= item.price %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin/items/new.html.erb
<h3>商品新規登録</h3>
  <%= form_with model: [:admin, @item], local: true do |f| %>
    <div class="row form-group">
      <label class="col-md-2 offset-md-2">商品画像</label>
      <div class="col-md-6"><%= f.file_field :item_image, accept: 'image/*' %></div>
    </div>
    <div class="row form-group">
      <label class="col-md-2 offset-md-2">商品名</label>
      <div class="col-md-6"><%= f.text_field :name, placeholder: "商品名", class: "form-control" %></div>
    </div>
    <div class="row form-group">
      <label class="col-md-2 offset-md-2">商品説明</label>
      <div class="col-md-6">
        <%= f.text_area :explanation, placeholder: "ここに説明文を記述します", class: "form-control", size: "100x10" %>
      </div>
    </div>
   
    <div class="row form-group">
      <label class="col-md-2 offset-md-2">税抜き価格</label>
      <div class="col-md-6"><%= f.text_field :price, placeholder: "1000", class: "form-control" %></div>円
    </div>
    <div class="row form-group">
      <label class="col-md-2 offset-md-2">販売ステータス</label>
      <div class="col-md-6">
        <%= f.radio_button :is_active, true, checked: true %>
        <%= f.label :is_active, "販売中", class: "mr-3" %>
        <%= f.radio_button :is_active, false %>
        <%= f.label :is_active, "販売停止中" %>
      </div>
    </div>
    <div class="row">
      <div class="col-md-2 offset-md-5">
        <% if f.object.new_record? %>
          <%= f.submit "新規登録", class: "btn-lg btn-success" %>
        <% else %>
          <%= f.submit "変更を保存", class: "btn-lg btn-success" %>
        <% end %>
      </div>
    </div>
  <% end %>

app/views/admin/items/show.html.erb
<div class="container-fluid"><br><br>
 <h4 class="col-lg-3 text-center bg-light mt-4">商品詳細</h1>
  <div class="row">
    <div class="col-1"></div>
    <div class="col-2"></div>
    <div class="col-3">
   <%=image_tag @item.item_image, size:'300x300' %>
   <div class="tag-box">
     <% @item.tags.each do |tag| %>
    <span class="label"><%= tag.name %></span>
    <% end %>
   </div>
    </div>
    <div class="col-4">
      <div class="row mt-3 mt-lg-2">
        <p class="col-lg-3">商品名</p>
        <h5 class="col-lg-9"><%= @item.name %></h5>
      </div>
       <div class="row mt-3 mt-lg-2">
        <p class="col-lg-3">税抜き価格</p>
       <h5 class="col-lg-9"><%= @item.price %>円</h5>
      </div>
      <div class="row mt-3 mt-lg-2">
        <p class="col-lg-3">税込み価格</p>
       <h5 class="col-lg-9"><%= @item.with_tax_price %>円</h5>
      </div>
    <div class="col-1"></div>
    <div class="row mt-4 text-center">
        <div class="col-auto offset-lg-2">
          <%= link_to "編集する", edit_admin_item_path(@item), class: "btn btn-success" %>
        </div>
      </div>
    </div>
    </div>
  </div>
</div>

app/views/admin/orders/index.html.erb
ssssssss

app/views/admin/orders/show.html.erb
<div class="container">

  <div class="col-sm-10">
    <h2 class="mt-5 mb-5">注文履歴詳細</h2>
    <%= notice %>
  </div>

  <div class="row">
    <div class="col-sm-8">
      <%= form_with model: @order, url: admin_order_path, method: :patch, local: true do |f| %>
        <table class="table">
            <tr>
              <th>購入者</th>
              <td class="link">
                <%= link_to admin_customer_path(@order.customer) do %>
                  <%= @order.customer.last_name + @order.customer.first_name %>
                <% end %>
              </td>
            </tr>
            <tr>
              <th>注文日</th>
              <td><%= @order.created_at.strftime("%Y-%m-%d %H:%M:%S") %></td>
            </tr>
            <tr>
              <th>配送先</th>
              <td>
                〒<%= @order.post_code.to_s.insert(3, "-") %><br>
                <%= @order.address %><br>
                <%= @order.name %>
              </td>
            </tr>
            <tr>
              <th>支払い方法</th>
              <td><%= @order.payment_option %></td>
            </tr>
        </table>
      <% end %>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-9">
      <table class="table table-bordered">
        <thead>
          <tr>
            <th class="table-active text-center col-4">商品名</th>
            <th class="table-active text-center col-2">単価(税込)</th>
            <th class="table-active text-center col-1">数量</th>
            <th class="table-active text-center col-2">小計</th>
          </tr>
        </thead>
        <tbody>
          <% @order.order_items.each do |order_detail| %>
          <tr>
            <td class="text-center"><%= order_detail.item.name %> </td>
            <td class="text-center"><%= order_detail.price.to_s(:delimited) %>円</td>
            <td class="text-center"><%= order_detail.quantity %></td>
            <td class="text-center"><%= (order_detail.price * order_detail.quantity).to_s(:delimited) %>円</td>
            <td class="text-right"></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <div class="col-sm-3">
      <table class="table table-bordered">
        <tr>
          <th class="table-active text-center">商品合計</th>
          <td class="text-right">
            <% @add_tax_total_payment = @order.total_price %>
            <%= @add_tax_total_payment.to_s(:delimited) %>円
          </td>
        </tr>
        <tr>
          <th class="table-active text-center">送料</th>
          <td class="text-right"><%= @order.shipping_fee %>円</td>
        </tr>
        <tr>
          <th class="table-active text-center">請求金額合計</th>
          <td class="text-right">
            <% @total_payment_add_shipping_fee = @add_tax_total_payment + @order.shipping_fee %>
            <%= @total_payment_add_shipping_fee.to_s(:delimited) %>円
          </td>
        </tr>
      </table>
    </div>
  </div>
</div>