config/routes.rb
Rails.application.routes.draw do
  
  devise_for :customers, controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}


 devise_for :admin, controllers: {
  sessions: "admin/sessions"
}


  scope module: :public do
    root :to => "homes#top"
    get "about" => "homes#about"
    get 'customers/my_page' => 'customers#show'
    get 'customers/information/edit' => 'customers#edit'
    patch 'customers/information/edit' => 'customers#update'
    get 'customers/confirm' => 'customers#confirm'
    patch 'customers/leave' => 'customers#leave'
    resources :items, only: [:index, :show]
    delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
    resources :cart_items, only: [:index, :update, :destroy, :create]
    get 'orders/complete' => 'orders#complete'
    resources :orders, only: [:new, :create, :index, :show]
    post 'orders/confirm' => 'orders#confirm'
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
    get "items/:id/genre_search" => "items#search", as: "genre_search"
  end
  namespace :admin do
    root :to =>  'homes#top'
    resources :customers, only: [:index, :show, :edit, :update]
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :orders, only: [:show, :update] do
      resources :order_items, only: [:update]
    end
  end
 

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
  validates :name, presence:true
  validates :address, presence:true
  validates :post_code, presence:true, length: { is: 7 }, numericality: true
  
  def address_display
    '〒' + post_code + '　宛先' + address + '　宛名' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item
  
  def with_tax_price
    (item.price * 1.1).floor
  end
  
  def subtotal_price
    item.with_tax_price * quantity
  end
  
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  validates :email, presence: true
  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_reading, presence: true, format: { with: /\A[\p{katakana}\p{blank}ー－]+\z/}
  validates :first_name_reading, presence: true, format: { with: /\A[\p{katakana}\p{blank}ー－]+\z/}
  validates :post_code, presence: true
  validates :address, presence: true
  validates :phone_number, presence: true

  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  
  
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :cart_items, dependent: :destroy
  has_many :order_items, dependent: :destroy
  has_many :tags

  validates :name, presence:true
  validates :explanation, presence:true
  validates :price, presence:true, numericality: {greater_than_or_equal_to: 1}

  has_one_attached :item_image
  
  def with_tax_price
    (price * 1.1).floor
  end

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_items, dependent: :destroy
 
 enum payment_option: { credit_card: 0, transfer: 1 }
 
 def address_display
    '〒' + post_code + '　宛先' + address + '　宛名' + name
 end
 
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :item
  belongs_to :order

end

app/models/tag.rb
class Tag < ApplicationRecord
  belongs_to :item
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
   def top
    @params = params[:id]
    @order = Order.where(customer_id: @params).order(created_at: :desc)
    @orders = Order.all
   end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

  def index
    @items = Item.all
  end
  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    tags = Vision.get_image_data(item_params[:item_image])
    if @item.save
      tags.each do |tag|
        @item.tags.create(name: tag)
      end
      redirect_to admin_item_path(@item)
    else
      render "new"
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path(@item)
    else
      render "edit"
    end
  end
   private

  def item_params
    params.require(:item).permit(:name, :explanation, :price, :is_active, :item_image)
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
   def show
    @order = Order.find(params[:id])
    @orders = Order.all
    
  
   end

  def update
    @order = Order.find(params[:id])
    @order_details = OrderItem.where(order_id: @order)

    
  end

  private

  
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_admin!, if: :admin_url 

  def admin_url
    request.fullpath.include?("/admin")
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_items_helper.rb
module Admin::OrderItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

app/views/layouts/_header.html.erb
<!--イラストロゴのリンク先-->
<% if admin_signed_in? %>
  <% @top_page_path = admin_root_path %>
<% else %>
  <% @top_page_path = root_path %>
<% end %>

<!--ヘッダー画面-->
<header>
  <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #5A9AFB;">
    <div class="col-lg-3">
     
      <div class="navbar-brand mb-auto">
        <%= link_to 'TOP', @top_page_path, class: "btn btn-outline-dark m-3" %>
      </div>
    </div>
      <!--メニューボタン-->
      <div class="col-auto mb-auto ml-lg-auto">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav">
            <% if admin_signed_in? %>
              <li><%= link_to '商品一覧', admin_items_path, class: "btn btn-outline-dark m-3" %></li>
              <li><%= link_to '会員一覧', admin_customers_path, class: "btn btn-outline-dark m-3" %></li>
              <li><%= link_to '注文履歴一覧', admin_root_path, class: "btn btn-outline-dark m-3" %></li>
              <li><%= link_to 'ログアウト', destroy_admin_session_path, method: :delete, class: "btn btn-outline-dark m-3" %></li>
            <% else %>
              <% if customer_signed_in? %>
                <li><%= link_to 'マイページ', customers_my_page_path, class: "btn btn-outline-dark m-3" %></li>
                <li><%= link_to '商品一覧', items_path, class: "btn btn-outline-dark m-3" %></li>
                <li><%= link_to 'カート', cart_items_path, class: "btn btn-outline-dark m-3" %></li>
                <li><%= link_to 'ログアウト', destroy_customer_session_path, method: :delete, class: "btn btn-outline-dark m-3" %></li>
              <% else %>
                <li><%= link_to 'About', about_path, class: "btn btn-outline-dark m-3" %></li>
                <li><%= link_to '商品一覧', items_path, class: "btn btn-outline-dark m-3" %></li>
                <li><%= link_to '新規登録', new_customer_registration_path, class: "btn btn-outline-dark m-3" %></li>
                <li><%= link_to 'ログイン', new_customer_session_path, class: "btn btn-outline-dark m-3" %></li>
              <% end %>
            <% end %>
          </ul>
        </div>
      </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Yoshizo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/b4cb9dd85e.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render '/layouts/header' %>
    <%= yield %>
  </body>
</html>